/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) crazyflie_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[93] = {9, 9, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s2[43] = {9, 4, 0, 9, 18, 27, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s3[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[3] = {0, 0, 0};

/* crazyflie_expl_vde_forw:(i0[9],i1[9x9],i2[9x4],i3[4],i4[])->(o0[9],o1[9x9],o2[9x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][6] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][7] : 0;
  a3=sin(a2);
  a4=(a1*a3);
  a5=arg[0]? arg[0][8] : 0;
  a6=cos(a5);
  a7=(a4*a6);
  a8=sin(a0);
  a9=sin(a5);
  a10=(a8*a9);
  a7=(a7+a10);
  a10=arg[3]? arg[3][3] : 0;
  a11=(a7*a10);
  a12=2.8000000000000001e-02;
  a11=(a11/a12);
  if (res[0]!=0) res[0][3]=a11;
  a11=(a1*a3);
  a13=(a11*a9);
  a14=(a8*a6);
  a13=(a13-a14);
  a14=(a13*a10);
  a14=(a14/a12);
  if (res[0]!=0) res[0][4]=a14;
  a14=-9.8066499999999994e+00;
  a15=cos(a2);
  a16=(a1*a15);
  a17=(a16*a10);
  a17=(a17/a12);
  a14=(a14+a17);
  if (res[0]!=0) res[0][5]=a14;
  a14=arg[3]? arg[3][0] : 0;
  a14=(a14-a0);
  a17=8.0000000000000002e-02;
  a14=(a14/a17);
  if (res[0]!=0) res[0][6]=a14;
  a14=arg[3]? arg[3][1] : 0;
  a14=(a14-a2);
  a14=(a14/a17);
  if (res[0]!=0) res[0][7]=a14;
  a14=arg[3]? arg[3][2] : 0;
  a14=(a14-a5);
  a14=(a14/a17);
  if (res[0]!=0) res[0][8]=a14;
  a14=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][0]=a14;
  a14=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][1]=a14;
  a14=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][2]=a14;
  a14=3.5714285714285715e+01;
  a17=cos(a2);
  a12=arg[1]? arg[1][7] : 0;
  a18=(a17*a12);
  a19=(a1*a18);
  a20=sin(a0);
  a21=arg[1]? arg[1][6] : 0;
  a22=(a20*a21);
  a23=(a3*a22);
  a19=(a19-a23);
  a19=(a6*a19);
  a23=sin(a5);
  a24=arg[1]? arg[1][8] : 0;
  a25=(a23*a24);
  a26=(a4*a25);
  a19=(a19-a26);
  a26=cos(a0);
  a27=(a26*a21);
  a28=(a9*a27);
  a29=cos(a5);
  a30=(a29*a24);
  a31=(a8*a30);
  a28=(a28+a31);
  a19=(a19+a28);
  a19=(a10*a19);
  a19=(a14*a19);
  if (res[1]!=0) res[1][3]=a19;
  a18=(a1*a18);
  a19=(a3*a22);
  a18=(a18-a19);
  a18=(a9*a18);
  a30=(a11*a30);
  a18=(a18+a30);
  a27=(a6*a27);
  a25=(a8*a25);
  a27=(a27-a25);
  a18=(a18-a27);
  a18=(a10*a18);
  a18=(a14*a18);
  if (res[1]!=0) res[1][4]=a18;
  a22=(a15*a22);
  a18=sin(a2);
  a27=(a18*a12);
  a27=(a1*a27);
  a22=(a22+a27);
  a22=(a10*a22);
  a22=(a14*a22);
  a22=(-a22);
  if (res[1]!=0) res[1][5]=a22;
  a22=1.2500000000000000e+01;
  a21=(a22*a21);
  a21=(-a21);
  if (res[1]!=0) res[1][6]=a21;
  a12=(a22*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][7]=a12;
  a24=(a22*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][8]=a24;
  a24=arg[1]? arg[1][12] : 0;
  if (res[1]!=0) res[1][9]=a24;
  a24=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][10]=a24;
  a24=arg[1]? arg[1][14] : 0;
  if (res[1]!=0) res[1][11]=a24;
  a24=arg[1]? arg[1][16] : 0;
  a12=(a17*a24);
  a21=(a1*a12);
  a27=arg[1]? arg[1][15] : 0;
  a25=(a20*a27);
  a30=(a3*a25);
  a21=(a21-a30);
  a21=(a6*a21);
  a30=arg[1]? arg[1][17] : 0;
  a19=(a23*a30);
  a28=(a4*a19);
  a21=(a21-a28);
  a28=(a26*a27);
  a31=(a9*a28);
  a32=(a29*a30);
  a33=(a8*a32);
  a31=(a31+a33);
  a21=(a21+a31);
  a21=(a10*a21);
  a21=(a14*a21);
  if (res[1]!=0) res[1][12]=a21;
  a12=(a1*a12);
  a21=(a3*a25);
  a12=(a12-a21);
  a12=(a9*a12);
  a32=(a11*a32);
  a12=(a12+a32);
  a28=(a6*a28);
  a19=(a8*a19);
  a28=(a28-a19);
  a12=(a12-a28);
  a12=(a10*a12);
  a12=(a14*a12);
  if (res[1]!=0) res[1][13]=a12;
  a25=(a15*a25);
  a12=(a18*a24);
  a12=(a1*a12);
  a25=(a25+a12);
  a25=(a10*a25);
  a25=(a14*a25);
  a25=(-a25);
  if (res[1]!=0) res[1][14]=a25;
  a27=(a22*a27);
  a27=(-a27);
  if (res[1]!=0) res[1][15]=a27;
  a24=(a22*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][16]=a24;
  a30=(a22*a30);
  a30=(-a30);
  if (res[1]!=0) res[1][17]=a30;
  a30=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][18]=a30;
  a30=arg[1]? arg[1][22] : 0;
  if (res[1]!=0) res[1][19]=a30;
  a30=arg[1]? arg[1][23] : 0;
  if (res[1]!=0) res[1][20]=a30;
  a30=arg[1]? arg[1][25] : 0;
  a24=(a17*a30);
  a27=(a1*a24);
  a25=arg[1]? arg[1][24] : 0;
  a12=(a20*a25);
  a28=(a3*a12);
  a27=(a27-a28);
  a27=(a6*a27);
  a28=arg[1]? arg[1][26] : 0;
  a19=(a23*a28);
  a32=(a4*a19);
  a27=(a27-a32);
  a32=(a26*a25);
  a21=(a9*a32);
  a31=(a29*a28);
  a33=(a8*a31);
  a21=(a21+a33);
  a27=(a27+a21);
  a27=(a10*a27);
  a27=(a14*a27);
  if (res[1]!=0) res[1][21]=a27;
  a24=(a1*a24);
  a27=(a3*a12);
  a24=(a24-a27);
  a24=(a9*a24);
  a31=(a11*a31);
  a24=(a24+a31);
  a32=(a6*a32);
  a19=(a8*a19);
  a32=(a32-a19);
  a24=(a24-a32);
  a24=(a10*a24);
  a24=(a14*a24);
  if (res[1]!=0) res[1][22]=a24;
  a12=(a15*a12);
  a24=(a18*a30);
  a24=(a1*a24);
  a12=(a12+a24);
  a12=(a10*a12);
  a12=(a14*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][23]=a12;
  a25=(a22*a25);
  a25=(-a25);
  if (res[1]!=0) res[1][24]=a25;
  a30=(a22*a30);
  a30=(-a30);
  if (res[1]!=0) res[1][25]=a30;
  a28=(a22*a28);
  a28=(-a28);
  if (res[1]!=0) res[1][26]=a28;
  a28=arg[1]? arg[1][30] : 0;
  if (res[1]!=0) res[1][27]=a28;
  a28=arg[1]? arg[1][31] : 0;
  if (res[1]!=0) res[1][28]=a28;
  a28=arg[1]? arg[1][32] : 0;
  if (res[1]!=0) res[1][29]=a28;
  a28=arg[1]? arg[1][34] : 0;
  a30=(a17*a28);
  a25=(a1*a30);
  a12=arg[1]? arg[1][33] : 0;
  a24=(a20*a12);
  a32=(a3*a24);
  a25=(a25-a32);
  a25=(a6*a25);
  a32=arg[1]? arg[1][35] : 0;
  a19=(a23*a32);
  a31=(a4*a19);
  a25=(a25-a31);
  a31=(a26*a12);
  a27=(a9*a31);
  a21=(a29*a32);
  a33=(a8*a21);
  a27=(a27+a33);
  a25=(a25+a27);
  a25=(a10*a25);
  a25=(a14*a25);
  if (res[1]!=0) res[1][30]=a25;
  a30=(a1*a30);
  a25=(a3*a24);
  a30=(a30-a25);
  a30=(a9*a30);
  a21=(a11*a21);
  a30=(a30+a21);
  a31=(a6*a31);
  a19=(a8*a19);
  a31=(a31-a19);
  a30=(a30-a31);
  a30=(a10*a30);
  a30=(a14*a30);
  if (res[1]!=0) res[1][31]=a30;
  a24=(a15*a24);
  a30=(a18*a28);
  a30=(a1*a30);
  a24=(a24+a30);
  a24=(a10*a24);
  a24=(a14*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][32]=a24;
  a12=(a22*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][33]=a12;
  a28=(a22*a28);
  a28=(-a28);
  if (res[1]!=0) res[1][34]=a28;
  a32=(a22*a32);
  a32=(-a32);
  if (res[1]!=0) res[1][35]=a32;
  a32=arg[1]? arg[1][39] : 0;
  if (res[1]!=0) res[1][36]=a32;
  a32=arg[1]? arg[1][40] : 0;
  if (res[1]!=0) res[1][37]=a32;
  a32=arg[1]? arg[1][41] : 0;
  if (res[1]!=0) res[1][38]=a32;
  a32=arg[1]? arg[1][43] : 0;
  a28=(a17*a32);
  a12=(a1*a28);
  a24=arg[1]? arg[1][42] : 0;
  a30=(a20*a24);
  a31=(a3*a30);
  a12=(a12-a31);
  a12=(a6*a12);
  a31=arg[1]? arg[1][44] : 0;
  a19=(a23*a31);
  a21=(a4*a19);
  a12=(a12-a21);
  a21=(a26*a24);
  a25=(a9*a21);
  a27=(a29*a31);
  a33=(a8*a27);
  a25=(a25+a33);
  a12=(a12+a25);
  a12=(a10*a12);
  a12=(a14*a12);
  if (res[1]!=0) res[1][39]=a12;
  a28=(a1*a28);
  a12=(a3*a30);
  a28=(a28-a12);
  a28=(a9*a28);
  a27=(a11*a27);
  a28=(a28+a27);
  a21=(a6*a21);
  a19=(a8*a19);
  a21=(a21-a19);
  a28=(a28-a21);
  a28=(a10*a28);
  a28=(a14*a28);
  if (res[1]!=0) res[1][40]=a28;
  a30=(a15*a30);
  a28=(a18*a32);
  a28=(a1*a28);
  a30=(a30+a28);
  a30=(a10*a30);
  a30=(a14*a30);
  a30=(-a30);
  if (res[1]!=0) res[1][41]=a30;
  a24=(a22*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][42]=a24;
  a32=(a22*a32);
  a32=(-a32);
  if (res[1]!=0) res[1][43]=a32;
  a31=(a22*a31);
  a31=(-a31);
  if (res[1]!=0) res[1][44]=a31;
  a31=arg[1]? arg[1][48] : 0;
  if (res[1]!=0) res[1][45]=a31;
  a31=arg[1]? arg[1][49] : 0;
  if (res[1]!=0) res[1][46]=a31;
  a31=arg[1]? arg[1][50] : 0;
  if (res[1]!=0) res[1][47]=a31;
  a31=arg[1]? arg[1][52] : 0;
  a32=(a17*a31);
  a24=(a1*a32);
  a30=arg[1]? arg[1][51] : 0;
  a28=(a20*a30);
  a21=(a3*a28);
  a24=(a24-a21);
  a24=(a6*a24);
  a21=arg[1]? arg[1][53] : 0;
  a19=(a23*a21);
  a27=(a4*a19);
  a24=(a24-a27);
  a27=(a26*a30);
  a12=(a9*a27);
  a25=(a29*a21);
  a33=(a8*a25);
  a12=(a12+a33);
  a24=(a24+a12);
  a24=(a10*a24);
  a24=(a14*a24);
  if (res[1]!=0) res[1][48]=a24;
  a32=(a1*a32);
  a24=(a3*a28);
  a32=(a32-a24);
  a32=(a9*a32);
  a25=(a11*a25);
  a32=(a32+a25);
  a27=(a6*a27);
  a19=(a8*a19);
  a27=(a27-a19);
  a32=(a32-a27);
  a32=(a10*a32);
  a32=(a14*a32);
  if (res[1]!=0) res[1][49]=a32;
  a28=(a15*a28);
  a32=(a18*a31);
  a32=(a1*a32);
  a28=(a28+a32);
  a28=(a10*a28);
  a28=(a14*a28);
  a28=(-a28);
  if (res[1]!=0) res[1][50]=a28;
  a30=(a22*a30);
  a30=(-a30);
  if (res[1]!=0) res[1][51]=a30;
  a31=(a22*a31);
  a31=(-a31);
  if (res[1]!=0) res[1][52]=a31;
  a21=(a22*a21);
  a21=(-a21);
  if (res[1]!=0) res[1][53]=a21;
  a21=arg[1]? arg[1][57] : 0;
  if (res[1]!=0) res[1][54]=a21;
  a21=arg[1]? arg[1][58] : 0;
  if (res[1]!=0) res[1][55]=a21;
  a21=arg[1]? arg[1][59] : 0;
  if (res[1]!=0) res[1][56]=a21;
  a21=arg[1]? arg[1][61] : 0;
  a31=(a17*a21);
  a30=(a1*a31);
  a28=arg[1]? arg[1][60] : 0;
  a32=(a20*a28);
  a27=(a3*a32);
  a30=(a30-a27);
  a30=(a6*a30);
  a27=arg[1]? arg[1][62] : 0;
  a19=(a23*a27);
  a25=(a4*a19);
  a30=(a30-a25);
  a25=(a26*a28);
  a24=(a9*a25);
  a12=(a29*a27);
  a33=(a8*a12);
  a24=(a24+a33);
  a30=(a30+a24);
  a30=(a10*a30);
  a30=(a14*a30);
  if (res[1]!=0) res[1][57]=a30;
  a31=(a1*a31);
  a30=(a3*a32);
  a31=(a31-a30);
  a31=(a9*a31);
  a12=(a11*a12);
  a31=(a31+a12);
  a25=(a6*a25);
  a19=(a8*a19);
  a25=(a25-a19);
  a31=(a31-a25);
  a31=(a10*a31);
  a31=(a14*a31);
  if (res[1]!=0) res[1][58]=a31;
  a32=(a15*a32);
  a31=(a18*a21);
  a31=(a1*a31);
  a32=(a32+a31);
  a32=(a10*a32);
  a32=(a14*a32);
  a32=(-a32);
  if (res[1]!=0) res[1][59]=a32;
  a28=(a22*a28);
  a28=(-a28);
  if (res[1]!=0) res[1][60]=a28;
  a21=(a22*a21);
  a21=(-a21);
  if (res[1]!=0) res[1][61]=a21;
  a27=(a22*a27);
  a27=(-a27);
  if (res[1]!=0) res[1][62]=a27;
  a27=arg[1]? arg[1][66] : 0;
  if (res[1]!=0) res[1][63]=a27;
  a27=arg[1]? arg[1][67] : 0;
  if (res[1]!=0) res[1][64]=a27;
  a27=arg[1]? arg[1][68] : 0;
  if (res[1]!=0) res[1][65]=a27;
  a27=arg[1]? arg[1][70] : 0;
  a21=(a17*a27);
  a28=(a1*a21);
  a32=arg[1]? arg[1][69] : 0;
  a31=(a20*a32);
  a25=(a3*a31);
  a28=(a28-a25);
  a28=(a6*a28);
  a25=arg[1]? arg[1][71] : 0;
  a19=(a23*a25);
  a12=(a4*a19);
  a28=(a28-a12);
  a12=(a26*a32);
  a30=(a9*a12);
  a24=(a29*a25);
  a33=(a8*a24);
  a30=(a30+a33);
  a28=(a28+a30);
  a28=(a10*a28);
  a28=(a14*a28);
  if (res[1]!=0) res[1][66]=a28;
  a21=(a1*a21);
  a28=(a3*a31);
  a21=(a21-a28);
  a21=(a9*a21);
  a24=(a11*a24);
  a21=(a21+a24);
  a12=(a6*a12);
  a19=(a8*a19);
  a12=(a12-a19);
  a21=(a21-a12);
  a21=(a10*a21);
  a21=(a14*a21);
  if (res[1]!=0) res[1][67]=a21;
  a31=(a15*a31);
  a21=(a18*a27);
  a21=(a1*a21);
  a31=(a31+a21);
  a31=(a10*a31);
  a31=(a14*a31);
  a31=(-a31);
  if (res[1]!=0) res[1][68]=a31;
  a32=(a22*a32);
  a32=(-a32);
  if (res[1]!=0) res[1][69]=a32;
  a27=(a22*a27);
  a27=(-a27);
  if (res[1]!=0) res[1][70]=a27;
  a25=(a22*a25);
  a25=(-a25);
  if (res[1]!=0) res[1][71]=a25;
  a25=arg[1]? arg[1][75] : 0;
  if (res[1]!=0) res[1][72]=a25;
  a25=arg[1]? arg[1][76] : 0;
  if (res[1]!=0) res[1][73]=a25;
  a25=arg[1]? arg[1][77] : 0;
  if (res[1]!=0) res[1][74]=a25;
  a25=arg[1]? arg[1][79] : 0;
  a17=(a17*a25);
  a27=(a1*a17);
  a32=arg[1]? arg[1][78] : 0;
  a20=(a20*a32);
  a31=(a3*a20);
  a27=(a27-a31);
  a27=(a6*a27);
  a31=arg[1]? arg[1][80] : 0;
  a23=(a23*a31);
  a21=(a4*a23);
  a27=(a27-a21);
  a26=(a26*a32);
  a21=(a9*a26);
  a29=(a29*a31);
  a12=(a8*a29);
  a21=(a21+a12);
  a27=(a27+a21);
  a27=(a10*a27);
  a27=(a14*a27);
  if (res[1]!=0) res[1][75]=a27;
  a17=(a1*a17);
  a27=(a3*a20);
  a17=(a17-a27);
  a17=(a9*a17);
  a29=(a11*a29);
  a17=(a17+a29);
  a26=(a6*a26);
  a23=(a8*a23);
  a26=(a26-a23);
  a17=(a17-a26);
  a17=(a10*a17);
  a17=(a14*a17);
  if (res[1]!=0) res[1][76]=a17;
  a20=(a15*a20);
  a18=(a18*a25);
  a18=(a1*a18);
  a20=(a20+a18);
  a20=(a10*a20);
  a20=(a14*a20);
  a20=(-a20);
  if (res[1]!=0) res[1][77]=a20;
  a32=(a22*a32);
  a32=(-a32);
  if (res[1]!=0) res[1][78]=a32;
  a25=(a22*a25);
  a25=(-a25);
  if (res[1]!=0) res[1][79]=a25;
  a31=(a22*a31);
  a31=(-a31);
  if (res[1]!=0) res[1][80]=a31;
  a31=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][0]=a31;
  a31=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][1]=a31;
  a31=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][2]=a31;
  a31=cos(a2);
  a25=arg[2]? arg[2][7] : 0;
  a32=(a31*a25);
  a20=(a1*a32);
  a18=sin(a0);
  a17=arg[2]? arg[2][6] : 0;
  a26=(a18*a17);
  a23=(a3*a26);
  a20=(a20-a23);
  a20=(a6*a20);
  a23=sin(a5);
  a29=arg[2]? arg[2][8] : 0;
  a27=(a23*a29);
  a21=(a4*a27);
  a20=(a20-a21);
  a0=cos(a0);
  a21=(a0*a17);
  a12=(a9*a21);
  a5=cos(a5);
  a19=(a5*a29);
  a24=(a8*a19);
  a12=(a12+a24);
  a20=(a20+a12);
  a20=(a10*a20);
  a20=(a14*a20);
  if (res[2]!=0) res[2][3]=a20;
  a32=(a1*a32);
  a20=(a3*a26);
  a32=(a32-a20);
  a32=(a9*a32);
  a19=(a11*a19);
  a32=(a32+a19);
  a21=(a6*a21);
  a27=(a8*a27);
  a21=(a21-a27);
  a32=(a32-a21);
  a32=(a10*a32);
  a32=(a14*a32);
  if (res[2]!=0) res[2][4]=a32;
  a26=(a15*a26);
  a2=sin(a2);
  a32=(a2*a25);
  a32=(a1*a32);
  a26=(a26+a32);
  a26=(a10*a26);
  a26=(a14*a26);
  a26=(-a26);
  if (res[2]!=0) res[2][5]=a26;
  a17=(a22*a17);
  a17=(a22-a17);
  if (res[2]!=0) res[2][6]=a17;
  a25=(a22*a25);
  a25=(-a25);
  if (res[2]!=0) res[2][7]=a25;
  a29=(a22*a29);
  a29=(-a29);
  if (res[2]!=0) res[2][8]=a29;
  a29=arg[2]? arg[2][12] : 0;
  if (res[2]!=0) res[2][9]=a29;
  a29=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][10]=a29;
  a29=arg[2]? arg[2][14] : 0;
  if (res[2]!=0) res[2][11]=a29;
  a29=arg[2]? arg[2][16] : 0;
  a25=(a31*a29);
  a17=(a1*a25);
  a26=arg[2]? arg[2][15] : 0;
  a32=(a18*a26);
  a21=(a3*a32);
  a17=(a17-a21);
  a17=(a6*a17);
  a21=arg[2]? arg[2][17] : 0;
  a27=(a23*a21);
  a19=(a4*a27);
  a17=(a17-a19);
  a19=(a0*a26);
  a20=(a9*a19);
  a12=(a5*a21);
  a24=(a8*a12);
  a20=(a20+a24);
  a17=(a17+a20);
  a17=(a10*a17);
  a17=(a14*a17);
  if (res[2]!=0) res[2][12]=a17;
  a25=(a1*a25);
  a17=(a3*a32);
  a25=(a25-a17);
  a25=(a9*a25);
  a12=(a11*a12);
  a25=(a25+a12);
  a19=(a6*a19);
  a27=(a8*a27);
  a19=(a19-a27);
  a25=(a25-a19);
  a25=(a10*a25);
  a25=(a14*a25);
  if (res[2]!=0) res[2][13]=a25;
  a32=(a15*a32);
  a25=(a2*a29);
  a25=(a1*a25);
  a32=(a32+a25);
  a32=(a10*a32);
  a32=(a14*a32);
  a32=(-a32);
  if (res[2]!=0) res[2][14]=a32;
  a26=(a22*a26);
  a26=(-a26);
  if (res[2]!=0) res[2][15]=a26;
  a29=(a22*a29);
  a29=(a22-a29);
  if (res[2]!=0) res[2][16]=a29;
  a21=(a22*a21);
  a21=(-a21);
  if (res[2]!=0) res[2][17]=a21;
  a21=arg[2]? arg[2][21] : 0;
  if (res[2]!=0) res[2][18]=a21;
  a21=arg[2]? arg[2][22] : 0;
  if (res[2]!=0) res[2][19]=a21;
  a21=arg[2]? arg[2][23] : 0;
  if (res[2]!=0) res[2][20]=a21;
  a21=arg[2]? arg[2][25] : 0;
  a29=(a31*a21);
  a26=(a1*a29);
  a32=arg[2]? arg[2][24] : 0;
  a25=(a18*a32);
  a19=(a3*a25);
  a26=(a26-a19);
  a26=(a6*a26);
  a19=arg[2]? arg[2][26] : 0;
  a27=(a23*a19);
  a12=(a4*a27);
  a26=(a26-a12);
  a12=(a0*a32);
  a17=(a9*a12);
  a20=(a5*a19);
  a24=(a8*a20);
  a17=(a17+a24);
  a26=(a26+a17);
  a26=(a10*a26);
  a26=(a14*a26);
  if (res[2]!=0) res[2][21]=a26;
  a29=(a1*a29);
  a26=(a3*a25);
  a29=(a29-a26);
  a29=(a9*a29);
  a20=(a11*a20);
  a29=(a29+a20);
  a12=(a6*a12);
  a27=(a8*a27);
  a12=(a12-a27);
  a29=(a29-a12);
  a29=(a10*a29);
  a29=(a14*a29);
  if (res[2]!=0) res[2][22]=a29;
  a25=(a15*a25);
  a29=(a2*a21);
  a29=(a1*a29);
  a25=(a25+a29);
  a25=(a10*a25);
  a25=(a14*a25);
  a25=(-a25);
  if (res[2]!=0) res[2][23]=a25;
  a32=(a22*a32);
  a32=(-a32);
  if (res[2]!=0) res[2][24]=a32;
  a21=(a22*a21);
  a21=(-a21);
  if (res[2]!=0) res[2][25]=a21;
  a19=(a22*a19);
  a19=(a22-a19);
  if (res[2]!=0) res[2][26]=a19;
  a19=arg[2]? arg[2][30] : 0;
  if (res[2]!=0) res[2][27]=a19;
  a19=arg[2]? arg[2][31] : 0;
  if (res[2]!=0) res[2][28]=a19;
  a19=arg[2]? arg[2][32] : 0;
  if (res[2]!=0) res[2][29]=a19;
  a7=(a14*a7);
  a19=arg[2]? arg[2][34] : 0;
  a31=(a31*a19);
  a21=(a1*a31);
  a32=arg[2]? arg[2][33] : 0;
  a18=(a18*a32);
  a25=(a3*a18);
  a21=(a21-a25);
  a21=(a6*a21);
  a25=arg[2]? arg[2][35] : 0;
  a23=(a23*a25);
  a4=(a4*a23);
  a21=(a21-a4);
  a0=(a0*a32);
  a4=(a9*a0);
  a5=(a5*a25);
  a29=(a8*a5);
  a4=(a4+a29);
  a21=(a21+a4);
  a21=(a10*a21);
  a21=(a14*a21);
  a7=(a7+a21);
  if (res[2]!=0) res[2][30]=a7;
  a13=(a14*a13);
  a31=(a1*a31);
  a3=(a3*a18);
  a31=(a31-a3);
  a9=(a9*a31);
  a11=(a11*a5);
  a9=(a9+a11);
  a6=(a6*a0);
  a8=(a8*a23);
  a6=(a6-a8);
  a9=(a9-a6);
  a9=(a10*a9);
  a9=(a14*a9);
  a13=(a13+a9);
  if (res[2]!=0) res[2][31]=a13;
  a16=(a14*a16);
  a15=(a15*a18);
  a2=(a2*a19);
  a1=(a1*a2);
  a15=(a15+a1);
  a10=(a10*a15);
  a14=(a14*a10);
  a16=(a16-a14);
  if (res[2]!=0) res[2][32]=a16;
  a32=(a22*a32);
  a32=(-a32);
  if (res[2]!=0) res[2][33]=a32;
  a19=(a22*a19);
  a19=(-a19);
  if (res[2]!=0) res[2][34]=a19;
  a22=(a22*a25);
  a22=(-a22);
  if (res[2]!=0) res[2][35]=a22;
  return 0;
}

CASADI_SYMBOL_EXPORT int crazyflie_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int crazyflie_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int crazyflie_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void crazyflie_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int crazyflie_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void crazyflie_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void crazyflie_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void crazyflie_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int crazyflie_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int crazyflie_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real crazyflie_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* crazyflie_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* crazyflie_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crazyflie_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crazyflie_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int crazyflie_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int crazyflie_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
